export const TASKCHAIN = 'TASKCHAIN';
export const NOTE_GET_INFO = 'NOTE_GET_INFO';
export const USER_SET_INIT_DATA = 'USER_SET_INIT_DATA';
export const GET_ALL_SHARE_DATA = 'GET_ALL_SHARE_DATA';
export const GET_NOTE_LIST_BY_SECTION = 'GET_NOTE_LIST_BY_SECTION';
export const GET_NOTE_LIST_BY_TAG = 'GET_NOTE_LIST_BY_TAG';
export const GET_NOTE_LIST_IN_TRASHCAN = 'GET_NOTE_LIST_IN_TRASHCAN';

// NOTEBOOK
export const NOTEBOOK_SET_LIST = 'NOTEBOOK_SET_LIST';
export const NOTEBOOK_REMOVE_ITEM_FROM_LIST = 'NOTEBOOK_REMOVE_ITEM_FROM_LIST';
export const NOTEBOOK_SET_SITE_NOTE_LIST = 'NOTEBOOK_SET_SITE_NOTE_LIST';
export const NOTEBOOK_INIT_SITE_NOTE_LIST = 'NOTEBOOK_INIT_SITE_NOTE_LIST';
export const NOTEBOOK_SET_MENU = 'NOTEBOOK_SET_MENU';
export const NOTEBOOK_SET_NOTE_LIST = 'NOTEBOOK_SET_NOTE_LIST';
export const NOTEBOOK_INIT_NOTE_LIST = 'NOTEBOOK_INIT_NOTE_LIST';
export const NOTEBOOK_INIT_TRASH_NOTE_LIST = 'NOTEBOOK_INIT_TRASH_NOTE_LIST';
export const NOTEBOOK_INIT_TRASH_RESTORE_NOTE_LIST = 'NOTEBOOK_INIT_TRASH_RESTORE_NOTE_LIST';
export const NOTEBOOK_SET_TAG_NOTE_LIST = 'NOTEBOOK_SET_TAG_NOTE_LIST';
export const NOTEBOOK_SET_MENU_ALIVE = 'NOTEBOOK_SET_MENU_ALIVE';
export const NOTEBOOK_SET_MENU_HIDE = 'NOTEBOOK_SET_MENU_HIDE';
export const NOTEBOOK_SET_MENU_WIDTH = 'NOTEBOOK_SET_MENU_WIDTH';
export const NOTEBOOK_ADD = 'NOTEBOOK_ADD';
export const NOTEBOOK_ADD_SECTION = 'NOTEBOOK_ADD_SECTION';
export const NOTEBOOK_ADD_NOTE = 'NOTEBOOK_ADD_NOTE';
export const NOTEBOOK_DELETE = 'NOTEBOOK_DELETE';
export const NOTEBOOK_DELETE_SECTION = 'NOTEBOOK_DELETE_SECTION';
export const NOTEBOOK_DELETE_NOTE = 'NOTEBOOK_DELETE_NOTE';
export const NOTEBOOK_DELETE_TRASH_NOTE = 'NOTEBOOK_DELETE_TRASH_NOTE';
export const NOTEBOOK_DELETE_SITENOTE = 'NOTEBOOK_DELETE_SITENOTE';
export const NOTEBOOK_RENAME_ACTION = 'NOTEBOOK_RENAME_ACTION';
export const NOTEBOOK_RENAME_CANCEL = 'NOTEBOOK_RENAME_CANCEL';
export const NOTEBOOK_SET_RENAME = 'NOTEBOOK_SET_RENAME';
export const NOTEBOOK_SET_RENAME_SECTION = 'NOTEBOOK_SET_RENAME_SECTION';
export const NOTEBOOK_SET_RENAME_NOTE = 'NOTEBOOK_SET_RENAME_NOTE';
export const NOTEBOOK_SET_BOOK_LIST = 'NOTEBOOK_SET_BOOK_LIST';
export const NOTEBOOK_SET_SEC_LIST = 'NOTEBOOK_SET_SEC_LIST';
export const NOTEBOOK_SET_SELECT_NOTE = 'NOTEBOOK_SET_SELECT_NOTE';
export const NOTEBOOK_SET_SELECTED_NOTE = 'NOTEBOOK_SET_SELECTED_NOTE';
export const NOTEBOOK_SET_SELECT_ITEM = 'NOTEBOOK_SET_SELECT_ITEM';
export const NOTEBOOK_SET_COLLAPSED_ITEM = 'NOTEBOOK_SET_COLLAPSED_ITEM';
export const NOTEBOOK_SET_FIRSTIN = 'NOTEBOOK_SET_FIRSTIN';
export const NOTEBOOK_SET_SECTION_MOVE = 'NOTEBOOK_SET_SECTION_MOVE';
export const NOTEBOOK_SET_MOVE_TO_INIT = 'NOTEBOOK_SET_MOVE_TO_INIT';
export const NOTEBOOK_SET_MOVE_TO_SITE_LIST = 'NOTEBOOK_SET_MOVE_TO_SITE_LIST';
export const NOTEBOOK_SET_MOVE_TO_BOOK_LIST = 'NOTEBOOK_SET_MOVE_TO_BOOK_LIST';
export const NOTEBOOK_SET_MOVE_TO_SEC_LIST = 'NOTEBOOK_SET_MOVE_TO_SEC_LIST';
export const NOTEBOOK_SET_MOVE_TO_SITE = 'NOTEBOOK_SET_MOVE_TO_SITE';
export const NOTEBOOK_GET_SYNC_INFO = 'NOTEBOOK_GET_SYNC_INFO';

export const NOTE_SET_TAG_LIST = 'NOTE_SET_TAG_LIST';
export const NOTE_SAVE_TAG_LIST = 'NOTE_SAVE_TAG_LIST';
export const NOTE_GET_RECENT_USE_TAG_LIST = 'NOTE_GET_RECENT_USE_TAG_LIST';
export const NOTE_SET_INFO = 'NOTE_SET_INFO';
export const NOTE_SET_MOVE = 'NOTE_SET_MOVE';
export const NOTE_SET_IMPORTANT = 'NOTE_SET_IMPORTANT';
export const NOTE_CANCEL_IMPORTANT = 'NOTE_CANCEL_IMPORTANT';
export const NOTE_CHANGE_UPLOAD_STATUS = 'NOTE_CHANGE_UPLOAD_STATUS';
export const NOTE_SET_SNAPSHOT_LIST = 'NOTE_SET_SNAPSHOT_LIST';
export const NOTE_GET_SNAPSHOT = 'NOTE_GET_SNAPSHOT';
export const NOTE_INIT_SNAPSHOT_INFO = 'NOTE_INIT_SNAPSHOT_INFO';

export const NOTEBOOK_TOGGLE_FULLSCREEN = 'NOTEBOOK_TOGGLE_FULLSCREEN';
export const NOTEBOOK_SHOW_NEXTCONTENT = 'NOTEBOOK_SHOW_NEXTCONTENT';
export const NOTEBOOK_SHOW_PREVCONTENT = 'NOTEBOOK_SHOW_PREVCONTENT';

export const SYS_SET_LANGUAGE = 'SYS_SET_LANGUAGE';
export const SYS_SET_FULLSCREEN = 'SYS_SET_FULLSCREEN';
export const SYS_SET_SIDEBAR_DISABLE = 'SYS_SET_SIDEBAR_DISABLE';
export const SYS_SET_WINDOW = 'SYS_SET_WINDOW';
export const SYS_SET_WINDOW_ERRORMESSAGE = 'SYS_SET_WINDOW_ERRORMESSAGE';
export const SYS_TEB_SELECT = 'SYS_TEB_SELECT';
export const SYS_SET_POPUP = 'SYS_SET_POPUP';
export const SYS_SET_MOUNT_CLOUD = 'SYS_SET_MOUNT_CLOUD';
export const SYS_SET_MOUNT_NAS = 'SYS_SET_MOUNT_NAS';
export const SYS_SET_MESSAGE = 'SYS_SET_MESSAGE';
export const SYS_POP_MESSAGE = 'SYS_POP_MESSAGE';
export const SYS_SET_REFRESH_TREE = 'SYS_SET_REFRESH_TREE';
export const SYS_SET_REFRESH_NOTE = 'SYS_SET_REFRESH_NOTE';
export const SYS_SET_REFRESH_TAG = 'SYS_SET_REFRESH_TAG';
export const SYS_SET_REFRESH_TAGNOTE = 'SYS_SET_REFRESH_TAGNOTE';
export const SYS_SET_REFRESH_SEARCH = 'SYS_SET_REFRESH_SEARCH';
export const SYS_SET_REFRESH_IMPORTANT = 'SYS_SET_REFRESH_IMPORTANT';
export const SYS_SET_GA = 'SYS_SET_GA';
export const SYS_ERROR_HANDLE = 'SYS_ERROR_HANDLE';

export const SYS_TOGGLE_LOADINGMASK = 'SYS_TOGGLE_LOADINGMASK';

// TAG
export const TAG_SET_SELECT_ITEM = 'TAG_SET_SELECT_ITEM';
export const TAG_SET_LIST = 'TAG_SET_LIST';
export const TAG_SET_INIT_LIST = 'TAG_SET_INIT_LIST';
export const TAG_SET_RENAME_ACTION = 'TAG_SET_RENAME_ACTION';
export const TAG_SET_RENAME = 'TAG_SET_RENAME';
export const TAG_DELETE = 'TAG_DELETE';

// SHARE
export const SHARE_SET_SITES = 'SHARE_SET_SITES';
export const SHARE_SET_SHAREWITHME = 'SHARE_SET_SHAREWITHME';
export const SHARE_SET_MYSHAREDDATA = 'SHARE_SET_MYSHAREDDATA';
export const SHARE_SET_PUBLISHEDLINK = 'SHARE_SET_PUBLISHEDLINK';
export const SHARE_SET_MYCONTACTS = 'SHARE_SET_MYCONTACTS';
export const SHARE_GET_PUBLIC_LINK = 'SHARE_GET_PUBLIC_LINK';
export const SHARE_INIT_PUBLIC_LINK = 'SHARE_INIT_PUBLIC_LINK';
export const SHARE_GET_ACCESS_LIST = 'SHARE_GET_ACCESS_LIST';
export const SHARE_INIT_SHARE_INFO = 'SHARE_INIT_SHARE_INFO';

// PUBLIC
export const SET_PUBLIC_TREE_LIST = 'SET_PUBLIC_TREE_LIST';
export const DECRYPT_PUBLIC_NOTE = 'DECRYPT_PUBLIC_NOTE';
export const PUBLIC_LINK_NOT_FOUND = 'PUBLIC_LINK_NOT_FOUND';
export const SET_PUBLIC_NOTE_INFO = 'SET_PUBLIC_NOTE_INFO';

// USER
export const USER_GET_INFO = 'GET_USER_INFO';
export const USER_GET_SITE_LIST = 'USER_GET_SITE_LIST';
export const USER_GET_LANGLIST = 'USER_GET_LANGLIST';
export const USER_SET_TUTORIAL = 'USER_SET_TUTORIAL';
export const USER_GET_SYNC_NOTEBOOK_LIST = 'USER_GET_SYNC_NOTEBOOK_LIST';
export const USER_GET_SYNC_SITE_LIST = 'USER_GET_SYNC_SITE_LIST';
export const USER_GET_SYNC_LIST = 'USER_GET_SYNC_LIST';
export const USER_SET_SYNC_POLICY = 'USER_SET_SYNC_POLICY';
export const USER_GET_SYNC_LOG = 'USER_GET_SYNC_LOG';
export const USER_GET_CONNECTION_LIST = 'USER_GET_CONNECTION_LIST';
export const USER_SET_SETTING = 'USER_SET_SETTING';

// EXPORT
export const EXPORT_GET_NOTEBOOKLIST = 'EXPORT_GET_NOTEBOOKLIST';

// Notification
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';
export const NOTIFICATION_READ = 'NOTIFICATION_READ';
export const NOTIFICATION_REFRESH = 'NOTIFICATION_REFRESH';
export const NOTIFICATION_CHANGE_MENU_STATE = 'NOTIFICATION_CHANGE_MENU_STATE';

// FILE_PREVIEW
export const FILE_PREVIEW_TOGGLE_FILE_PREVIEW = 'FILE_PREVIEW_TOGGLE_FILE_PREVIEW';
export const FILE_PREVIEW_TOGGLE_SIZE_BOX = 'FILE_PREVIEW_TOGGLE_SIZE_BOX';
export const FILE_PREVIEW_TOGGLE_TOOLBAR = 'FILE_PREVIEW_TOGGLE_TOOLBAR';
export const FILE_PREVIEW_TOGGLE_FILE_LIST = 'FILE_PREVIEW_TOGGLE_FILE_LIST';
export const FILE_PREVIEW_SET_IS_RESIZABLE = 'FILE_PREVIEW_SET_IS_RESIZABLE';
export const FILE_PREVIEW_SET_IS_WINDOW_RESIZE = 'FILE_PREVIEW_SET_IS_WINDOW_RESIZE';
export const FILE_PREVIEW_SET_IS_TOOLBAR_SHOW = 'FILE_PREVIEW_SET_IS_TOOLBAR_SHOW';
export const FILE_PREVIEW_SET_IMG_SIZE = 'FILE_PREVIEW_SET_IMG_SIZE';
export const FILE_PREVIEW_SET_IMG_ORIGIN_SIZE = 'FILE_PREVIEW_SET_IMG_ORIGIN_SIZE';
export const FILE_PREVIEW_SET_IMG_SCALE = 'FILE_PREVIEW_SET_IMG_SCALE';
export const FILE_PREVIEW_SET_IMG_OFFSET = 'FILE_PREVIEW_SET_IMG_OFFSET';
export const FILE_PREVIEW_SET_FILE_INDEX = 'FILE_PREVIEW_SET_FILE_INDEX';
export const FILE_PREVIEW_SET_FILE_LIST = 'FILE_PREVIEW_SET_FILE_LIST';
export const FILE_PREVIEW_INITIALIZE_STATUS = 'FILE_PREVIEW_INITIALIZE_STATUS';

// NAS
export const NAS_SET_DIR = 'NAS_SET_DIR';
export const NAS_SET_FOLDER_TREE = 'NAS_SET_FOLDER_TREE';
export const NAS_SET_FILE_LIST = 'NAS_SET_FILE_LIST';
export const NAS_INIT_FOLDER_FILE = 'NAS_INIT_FOLDER_FILE';
export const NAS_SET_SITE_LIST = 'NAS_SET_SITE_LIST';
