
export const EDITOR_UPDATE = 'EDITOR_UPDATE';
export const EDITOR_DELETE = 'EDITOR_DELETE';
export const EDITOR_JOIN_NOTE_ROOM = 'EDITOR_JOIN_NOTE_ROOM';
export const EDITOR_SET_EDITOR = 'EDITOR_SET_EDITOR';
export const EDITOR_SELECTION_CHANGE = 'EDITOR_SELECTION_CHANGE';
export const EDITOR_UPDATE_CONNS = 'EDITOR_UPDATE_CONNS';
export const EDITOR_UPDATE_COVER = 'EDITOR_UPDATE_COVER';
export const EDITOR_CHANGE_MODE = 'EDITOR_CHANGE_MODE';
export const EDITOR_STEPS_HANDLE = 'EDITOR_STEPS_HANDLE';
export const EDITOR_ERROR = 'EDITOR_ERROR';
export const EDITOR_SYNC = 'EDITOR_SYNC';
export const EDITOR_RELOAD = "EDITOR_RELOAD";
